-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SurveyAPI.Object.Survey exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SurveyAPI.InputObject
import SurveyAPI.Interface
import SurveyAPI.Object
import SurveyAPI.Scalar
import SurveyAPI.ScalarCodecs
import SurveyAPI.Union


{-| The document's ID.
-}
id_ : SelectionSet SurveyAPI.ScalarCodecs.Id SurveyAPI.Object.Survey
id_ =
    Object.selectionForField "ScalarCodecs.Id" "_id" [] (SurveyAPI.ScalarCodecs.codecs |> SurveyAPI.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The document's timestamp.
-}
ts_ : SelectionSet SurveyAPI.ScalarCodecs.Long SurveyAPI.Object.Survey
ts_ =
    Object.selectionForField "ScalarCodecs.Long" "_ts" [] (SurveyAPI.ScalarCodecs.codecs |> SurveyAPI.Scalar.unwrapCodecs |> .codecLong |> .decoder)


date : SelectionSet SurveyAPI.ScalarCodecs.Time SurveyAPI.Object.Survey
date =
    Object.selectionForField "ScalarCodecs.Time" "date" [] (SurveyAPI.ScalarCodecs.codecs |> SurveyAPI.Scalar.unwrapCodecs |> .codecTime |> .decoder)


questions :
    SelectionSet decodesTo SurveyAPI.Object.Question
    -> SelectionSet (List (Maybe decodesTo)) SurveyAPI.Object.Survey
questions object_ =
    Object.selectionForCompositeField "questions" [] object_ (identity >> Decode.nullable >> Decode.list)
