-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SurveyAPI.Object exposing (..)


type Question
    = Question


type Survey
    = Survey
