-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SurveyAPI.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import SurveyAPI.Scalar exposing (defaultCodecs)


type alias Date =
    SurveyAPI.Scalar.Date


type alias Id =
    SurveyAPI.Scalar.Id


type alias Long =
    SurveyAPI.Scalar.Long


type alias Time =
    SurveyAPI.Scalar.Time


codecs : SurveyAPI.Scalar.Codecs Date Id Long Time
codecs =
    SurveyAPI.Scalar.defineCodecs
        { codecDate = defaultCodecs.codecDate
        , codecId = defaultCodecs.codecId
        , codecLong = defaultCodecs.codecLong
        , codecTime = defaultCodecs.codecTime
        }
